# Student Alcohol Consumption

### Introduction:

This time you will download a dataset from the UCI.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv).

### Step 3. Assign it to a variable called df.

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv")

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [4]:
df.loc[:,'school':'guardian']

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father
5,GP,M,16,U,LE3,T,4,3,services,other,reputation,mother
6,GP,M,16,U,LE3,T,2,2,other,other,home,mother
7,GP,F,17,U,GT3,A,4,4,other,teacher,home,mother
8,GP,M,15,U,LE3,A,3,2,services,other,home,mother
9,GP,M,15,U,GT3,T,3,4,other,other,home,mother
10,GP,F,15,U,GT3,T,4,4,teacher,health,reputation,mother
11,GP,F,15,U,GT3,T,2,1,services,other,reputation,father
12,GP,M,15,U,LE3,T,4,4,health,services,course,father
13,GP,M,15,U,GT3,T,4,3,teacher,other,course,mother
14,GP,M,15,U,GT3,A,2,2,other,other,home,other
15,GP,F,16,U,GT3,T,4,4,health,other,home,mother
16,GP,F,16,U,GT3,T,4,4,services,services,reputation,mother
17,GP,F,16,U,GT3,T,3,3,other,other,reputation,mother
18,GP,M,17,U,GT3,T,3,2,services,services,course,mother
19,GP,M,16,U,LE3,T,4,3,health,other,home,father
20,GP,M,15,U,GT3,T,4,3,teacher,other,reputation,mother
21,GP,M,15,U,GT3,T,4,4,health,health,other,father
22,GP,M,16,U,LE3,T,4,2,teacher,other,course,mother
23,GP,M,16,U,LE3,T,2,2,other,other,reputation,mother
24,GP,F,15,R,GT3,T,2,4,services,health,course,mother
25,GP,F,16,U,GT3,T,2,2,services,services,home,mother
26,GP,M,15,U,GT3,T,2,2,other,other,home,mother
27,GP,M,15,U,GT3,T,4,2,health,services,other,mother
28,GP,M,16,U,LE3,A,3,4,services,other,home,mother
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,home,mother
...,...,...,...,...,...,...,...,...,...,...,...,...
365,MS,M,18,R,GT3,T,1,3,at_home,other,course,mother
366,MS,M,18,U,LE3,T,4,4,teacher,services,other,mother
367,MS,F,17,R,GT3,T,1,1,other,services,reputation,mother
368,MS,F,18,U,GT3,T,2,3,at_home,services,course,father
369,MS,F,18,R,GT3,T,4,4,other,teacher,other,father
370,MS,F,19,U,LE3,T,3,2,services,services,home,other
371,MS,M,18,R,LE3,T,1,2,at_home,services,other,father
372,MS,F,17,U,GT3,T,2,2,other,at_home,home,mother
373,MS,F,17,R,GT3,T,1,2,other,other,course,mother
374,MS,F,18,R,LE3,T,4,4,other,other,reputation,mother
375,MS,F,18,R,GT3,T,1,1,other,other,home,mother
376,MS,F,20,U,GT3,T,4,2,health,other,course,other
377,MS,F,18,R,LE3,T,4,4,teacher,services,course,mother
378,MS,F,18,U,GT3,T,3,3,other,other,home,mother
379,MS,F,17,R,GT3,T,3,1,at_home,other,reputation,mother
380,MS,M,18,U,GT3,T,4,4,teacher,teacher,home,father
381,MS,M,18,R,GT3,T,2,1,other,other,other,mother
382,MS,M,17,U,GT3,T,2,3,other,services,home,father
383,MS,M,19,R,GT3,T,1,1,other,services,other,mother
384,MS,M,18,R,GT3,T,4,2,other,other,home,father
385,MS,F,18,R,GT3,T,2,2,at_home,other,other,mother
386,MS,F,18,R,GT3,T,4,4,teacher,at_home,reputation,mother
387,MS,F,19,R,GT3,T,2,3,services,other,course,mother
388,MS,F,18,U,LE3,T,3,1,teacher,services,course,mother
389,MS,F,18,U,GT3,T,1,1,other,other,course,mother
390,MS,M,20,U,LE3,A,2,2,services,services,course,other
391,MS,M,17,U,LE3,T,3,1,services,services,course,mother
392,MS,M,21,R,GT3,T,1,1,other,other,course,other
393,MS,M,18,R,LE3,T,3,2,services,other,course,mother
394,MS,M,19,U,LE3,T,1,1,other,at_home,course,father

### Step 5. Create a lambda function that capitalize strings.

### Step 6. Capitalize both Mjob and Fjob

In [9]:
df['Mjob'] = df['Mjob'].apply(lambda x: x.capitalize())
df['Fjob'] = df['Fjob'].apply(lambda x: x.capitalize())
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,At_home,Other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,At_home,Other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,Health,Services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,Other,Other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,Services,Other,...,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,Other,Other,...,4,4,4,1,1,3,0,12,12,11
7,GP,F,17,U,GT3,A,4,4,Other,Teacher,...,4,1,4,1,1,1,6,6,5,6
8,GP,M,15,U,LE3,A,3,2,Services,Other,...,4,2,2,1,1,1,0,16,18,19
9,GP,M,15,U,GT3,T,3,4,Other,Other,...,5,5,1,1,1,5,0,14,15,15
10,GP,F,15,U,GT3,T,4,4,Teacher,Health,...,3,3,3,1,2,2,0,10,8,9
11,GP,F,15,U,GT3,T,2,1,Services,Other,...,5,2,2,1,1,4,4,10,12,12
12,GP,M,15,U,LE3,T,4,4,Health,Services,...,4,3,3,1,3,5,2,14,14,14
13,GP,M,15,U,GT3,T,4,3,Teacher,Other,...,5,4,3,1,2,3,2,10,10,11
14,GP,M,15,U,GT3,A,2,2,Other,Other,...,4,5,2,1,1,3,0,14,16,16
15,GP,F,16,U,GT3,T,4,4,Health,Other,...,4,4,4,1,2,2,4,14,14,14
16,GP,F,16,U,GT3,T,4,4,Services,Services,...,3,2,3,1,2,2,6,13,14,14
17,GP,F,16,U,GT3,T,3,3,Other,Other,...,5,3,2,1,1,4,4,8,10,10
18,GP,M,17,U,GT3,T,3,2,Services,Services,...,5,5,5,2,4,5,16,6,5,5
19,GP,M,16,U,LE3,T,4,3,Health,Other,...,3,1,3,1,3,5,4,8,10,10
20,GP,M,15,U,GT3,T,4,3,Teacher,Other,...,4,4,1,1,1,1,0,13,14,15
21,GP,M,15,U,GT3,T,4,4,Health,Health,...,5,4,2,1,1,5,0,12,15,15
22,GP,M,16,U,LE3,T,4,2,Teacher,Other,...,4,5,1,1,3,5,2,15,15,16
23,GP,M,16,U,LE3,T,2,2,Other,Other,...,5,4,4,2,4,5,0,13,13,12
24,GP,F,15,R,GT3,T,2,4,Services,Health,...,4,3,2,1,1,5,2,10,9,8
25,GP,F,16,U,GT3,T,2,2,Services,Services,...,1,2,2,1,3,5,14,6,9,8
26,GP,M,15,U,GT3,T,2,2,Other,Other,...,4,2,2,1,2,5,2,12,12,11
27,GP,M,15,U,GT3,T,4,2,Health,Services,...,2,2,4,2,4,1,4,15,16,15
28,GP,M,16,U,LE3,A,3,4,Services,Other,...,5,3,3,1,1,5,4,11,11,11
29,GP,M,16,U,GT3,T,4,4,Teacher,Teacher,...,4,4,5,5,5,5,16,10,12,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,MS,M,18,R,GT3,T,1,3,At_home,Other,...,3,3,4,2,4,3,4,10,10,10
366,MS,M,18,U,LE3,T,4,4,Teacher,Services,...,4,2,2,2,2,5,0,13,13,13
367,MS,F,17,R,GT3,T,1,1,Other,Services,...,5,2,1,1,2,1,0,7,6,0
368,MS,F,18,U,GT3,T,2,3,At_home,Services,...,5,2,3,1,2,4,0,11,10,10
369,MS,F,18,R,GT3,T,4,4,Other,Teacher,...,3,2,2,4,2,5,10,14,12,11
370,MS,F,19,U,LE3,T,3,2,Services,Services,...,3,2,2,1,1,3,4,7,7,9
371,MS,M,18,R,LE3,T,1,2,At_home,Services,...,4,3,3,2,3,3,3,14,12,12
372,MS,F,17,U,GT3,T,2,2,Other,At_home,...,3,4,3,1,1,3,8,13,11,11
373,MS,F,17,R,GT3,T,1,2,Other,Other,...,3,5,5,1,3,1,14,6,5,5
374,MS,F,18,R,LE3,T,4,4,Other,Other,...,5,4,4,1,1,1,0,19,18,19
375,MS,F,18,R,GT3,T,1,1,Other,Other,...,4,3,2,1,2,4,2,8,8,10
376,MS,F,20,U,GT3,T,4,2,Health,Other,...,5,4,3,1,1,3,4,15,14,15
377,MS,F,18,R,LE3,T,4,4,Teacher,Services,...,5,4,3,3,4,2,4,8,9,10
378,MS,F,18,U,GT3,T,3,3,Other,Other,...,4,1,3,1,2,1,0,15,15,15
379,MS,F,17,R,GT3,T,3,1,At_home,Other,...,4,5,4,2,3,1,17,10,10,10
380,MS,M,18,U,GT3,T,4,4,Teacher,Teacher,...,3,2,4,1,4,2,4,15,14,14
381,MS,M,18,R,GT3,T,2,1,Other,Other,...,4,4,3,1,3,5,5,7,6,7
382,MS,M,17,U,GT3,T,2,3,Other,Services,...,4,4,3,1,1,3,2,11,11,10
383,MS,M,19,R,GT3,T,1,1,Other,Services,...,4,3,2,1,3,5,0,6,5,0
384,MS,M,18,R,GT3,T,4,2,Other,Other,...,5,4,3,4,3,3,14,6,5,5
385,MS,F,18,R,GT3,T,2,2,At_home,Other,...,5,3,3,1,3,4,2,10,9,10
386,MS,F,18,R,GT3,T,4,4,Teacher,At_home,...,4,4,3,2,2,5,7,6,5,6
387,MS,F,19,R,GT3,T,2,3,Services,Other,...,5,4,2,1,2,5,0,7,5,0
388,MS,F,18,U,LE3,T,3,1,Teacher,Services,...,4,3,4,1,1,1,0,7,9,8
389,MS,F,18,U,GT3,T,1,1,Other,Other,...,1,1,1,1,1,5,0,6,5,0
390,MS,M,20,U,LE3,A,2,2,Services,Services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,Services,Services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,Other,Other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,Services,Other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,Other,At_home,...,3,2,3,3,3,5,5,8,9,9

### Step 7. Print the last elements of the data set.

In [10]:
df.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
390,MS,M,20,U,LE3,A,2,2,Services,Services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,Services,Services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,Other,Other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,Services,Other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,Other,At_home,...,3,2,3,3,3,5,5,8,9,9

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and capitalize Mjob and Fjob.

### Step 9. Create a function called majority that return a boolean value to a new column called legal_drinker (Consider majority as older than 17 years old)

In [12]:
df['legal_drinker'] = df['age'].apply(lambda x: 1 if x > 17 else 0)

In [13]:
df['legal_drinker']

0      1
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
365    1
366    1
367    0
368    1
369    1
370    1
371    1
372    0
373    0
374    1
375    1
376    1
377    1
378    1
379    0
380    1
381    1
382    0
383    1
384    1
385    1
386    1
387    1
388    1
389    1
390    1
391    0
392    1
393    1
394    1
Name: legal_drinker, Length: 395, dtype: int64

### Step 10. Multiply every number of the dataset by 10. 
##### I know this makes no sense, don't forget it is just an exercise

In [15]:
df[df.select_dtypes(include=['number']).columns] *= 10

In [16]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,legal_drinker
0,GP,F,180,U,GT3,A,40,40,At_home,Teacher,...,30,40,10,10,30,60,50,60,60,10
1,GP,F,170,U,GT3,T,10,10,At_home,Other,...,30,30,10,10,30,40,50,50,60,0
2,GP,F,150,U,LE3,T,10,10,At_home,Other,...,30,20,20,30,30,100,70,80,100,0
3,GP,F,150,U,GT3,T,40,20,Health,Services,...,20,20,10,10,50,20,150,140,150,0
4,GP,F,160,U,GT3,T,30,30,Other,Other,...,30,20,10,20,50,40,60,100,100,0
5,GP,M,160,U,LE3,T,40,30,Services,Other,...,40,20,10,20,50,100,150,150,150,0
6,GP,M,160,U,LE3,T,20,20,Other,Other,...,40,40,10,10,30,0,120,120,110,0
7,GP,F,170,U,GT3,A,40,40,Other,Teacher,...,10,40,10,10,10,60,60,50,60,0
8,GP,M,150,U,LE3,A,30,20,Services,Other,...,20,20,10,10,10,0,160,180,190,0
9,GP,M,150,U,GT3,T,30,40,Other,Other,...,50,10,10,10,50,0,140,150,150,0
10,GP,F,150,U,GT3,T,40,40,Teacher,Health,...,30,30,10,20,20,0,100,80,90,0
11,GP,F,150,U,GT3,T,20,10,Services,Other,...,20,20,10,10,40,40,100,120,120,0
12,GP,M,150,U,LE3,T,40,40,Health,Services,...,30,30,10,30,50,20,140,140,140,0
13,GP,M,150,U,GT3,T,40,30,Teacher,Other,...,40,30,10,20,30,20,100,100,110,0
14,GP,M,150,U,GT3,A,20,20,Other,Other,...,50,20,10,10,30,0,140,160,160,0
15,GP,F,160,U,GT3,T,40,40,Health,Other,...,40,40,10,20,20,40,140,140,140,0
16,GP,F,160,U,GT3,T,40,40,Services,Services,...,20,30,10,20,20,60,130,140,140,0
17,GP,F,160,U,GT3,T,30,30,Other,Other,...,30,20,10,10,40,40,80,100,100,0
18,GP,M,170,U,GT3,T,30,20,Services,Services,...,50,50,20,40,50,160,60,50,50,0
19,GP,M,160,U,LE3,T,40,30,Health,Other,...,10,30,10,30,50,40,80,100,100,0
20,GP,M,150,U,GT3,T,40,30,Teacher,Other,...,40,10,10,10,10,0,130,140,150,0
21,GP,M,150,U,GT3,T,40,40,Health,Health,...,40,20,10,10,50,0,120,150,150,0
22,GP,M,160,U,LE3,T,40,20,Teacher,Other,...,50,10,10,30,50,20,150,150,160,0
23,GP,M,160,U,LE3,T,20,20,Other,Other,...,40,40,20,40,50,0,130,130,120,0
24,GP,F,150,R,GT3,T,20,40,Services,Health,...,30,20,10,10,50,20,100,90,80,0
25,GP,F,160,U,GT3,T,20,20,Services,Services,...,20,20,10,30,50,140,60,90,80,0
26,GP,M,150,U,GT3,T,20,20,Other,Other,...,20,20,10,20,50,20,120,120,110,0
27,GP,M,150,U,GT3,T,40,20,Health,Services,...,20,40,20,40,10,40,150,160,150,0
28,GP,M,160,U,LE3,A,30,40,Services,Other,...,30,30,10,10,50,40,110,110,110,0
29,GP,M,160,U,GT3,T,40,40,Teacher,Teacher,...,40,50,50,50,50,160,100,120,110,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,MS,M,180,R,GT3,T,10,30,At_home,Other,...,30,40,20,40,30,40,100,100,100,10
366,MS,M,180,U,LE3,T,40,40,Teacher,Services,...,20,20,20,20,50,0,130,130,130,10
367,MS,F,170,R,GT3,T,10,10,Other,Services,...,20,10,10,20,10,0,70,60,0,0
368,MS,F,180,U,GT3,T,20,30,At_home,Services,...,20,30,10,20,40,0,110,100,100,10
369,MS,F,180,R,GT3,T,40,40,Other,Teacher,...,20,20,40,20,50,100,140,120,110,10
370,MS,F,190,U,LE3,T,30,20,Services,Services,...,20,20,10,10,30,40,70,70,90,10
371,MS,M,180,R,LE3,T,10,20,At_home,Services,...,30,30,20,30,30,30,140,120,120,10
372,MS,F,170,U,GT3,T,20,20,Other,At_home,...,40,30,10,10,30,80,130,110,110,0
373,MS,F,170,R,GT3,T,10,20,Other,Other,...,50,50,10,30,10,140,60,50,50,0
374,MS,F,180,R,LE3,T,40,40,Other,Other,...,40,40,10,10,10,0,190,180,190,10
375,MS,F,180,R,GT3,T,10,10,Other,Other,...,30,20,10,20,40,20,80,80,100,10
376,MS,F,200,U,GT3,T,40,20,Health,Other,...,40,30,10,10,30,40,150,140,150,10
377,MS,F,180,R,LE3,T,40,40,Teacher,Services,...,40,30,30,40,20,40,80,90,100,10
378,MS,F,180,U,GT3,T,30,30,Other,Other,...,10,30,10,20,10,0,150,150,150,10
379,MS,F,170,R,GT3,T,30,10,At_home,Other,...,50,40,20,30,10,170,100,100,100,0
380,MS,M,180,U,GT3,T,40,40,Teacher,Teacher,...,20,40,10,40,20,40,150,140,140,10
381,MS,M,180,R,GT3,T,20,10,Other,Other,...,40,30,10,30,50,50,70,60,70,10
382,MS,M,170,U,GT3,T,20,30,Other,Services,...,40,30,10,10,30,20,110,110,100,0
383,MS,M,190,R,GT3,T,10,10,Other,Services,...,30,20,10,30,50,0,60,50,0,10
384,MS,M,180,R,GT3,T,40,20,Other,Other,...,40,30,40,30,30,140,60,50,50,10
385,MS,F,180,R,GT3,T,20,20,At_home,Other,...,30,30,10,30,40,20,100,90,100,10
386,MS,F,180,R,GT3,T,40,40,Teacher,At_home,...,40,30,20,20,50,70,60,50,60,10
387,MS,F,190,R,GT3,T,20,30,Services,Other,...,40,20,10,20,50,0,70,50,0,10
388,MS,F,180,U,LE3,T,30,10,Teacher,Services,...,30,40,10,10,10,0,70,90,80,10
389,MS,F,180,U,GT3,T,10,10,Other,Other,...,10,10,10,10,50,0,60,50,0,10
390,MS,M,200,U,LE3,A,20,20,Services,Services,...,50,40,40,50,40,110,90,90,90,10
391,MS,M,170,U,LE3,T,30,10,Services,Services,...,40,50,30,40,20,30,140,160,160,0
392,MS,M,210,R,GT3,T,10,10,Other,Other,...,50,30,30,30,30,30,100,80,70,10
393,MS,M,180,R,LE3,T,30,20,Services,Other,...,40,10,30,40,50,0,110,120,100,10
394,MS,M,190,U,LE3,T,10,10,Other,At_home,...,20,30,30,30,50,50,80,90,90,10